name: Publish Image to NPM
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main

# Ensure only a single instance of this workflow is running.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for all tags and branches

      - name: Npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: "npm"

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_READ }}

      - name: Publish
        run: ./scripts/publish-if-not-exists.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_WRITE }}
